
class MetroLine {
  final String name;
  final List<String> stations;

  MetroLine({required this.name, required this.stations});
}

// All metro lines and stations data
final List<MetroLine> allMetroLines = [
  MetroLine(
    name: 'M1A',
    stations: [
      'ATAKÖY-ŞİRİNEVLER',
      'BAHÇELİEVLER',
      'TERAZİDERE',
      'KOCATEPE',
      'EMNİYET-FATİH',
      'AKSARAY A ÇIKIŞI',
    ],
  ),
  MetroLine(
    name: 'M1B',
    stations: [
      'KİRAZLI-BAĞCILAR 1',
      'KİRAZLI-BAĞCILAR 2',
      'BAĞCILAR MEYDAN',
    ],
  ),
  MetroLine(
    name: 'M2',
    stations: [
      'YENİKAPI 1 - HAMİDİYE SU / CODE 16',
      'YENİKAPI 2 - BÜFE YANI / CODE 15',
      'YENİKAPI - ÖZSÜT KARŞISI - 17',
      'YENİKAPI 4 - SİMİT SARAYI / CODE 14',
      'YENİKAPI 5',
      'VEZNECİLER-İSTANBUL Ü',
      'VEZNECİLER 2',
      'HALİÇ YENİKAPI YÖNÜ',
      'HALİÇ HACIOSMAN YÖNÜ',
      'ŞİŞHANE 1',
      'ŞİŞHANE 2',
      'TAKSİM 1 - FİNİKÜLER SAĞ - 65',
      'TAKSİM 2 - FİNİKÜLER SOL - 66',
      'TAKSİM 3 BANKMATİK YANI - 67',
      'TAKSİM 4 HAMİDİYE SU - 68',
      'TAKSİM 5 OTOBÜS - 69',
      'OSMANBEY',
      'OSMANBEY 2',
      'GAYRETTEPE 1',
      'GAYRETTEPE 2',
      'LEVENT 1 METROCİTY',
      'LEVENT 2 ÖZDİLEK',
      '4.LEVENT 1',
      '4.LEVENT 2',
      'SANAYİ MAHALLESİ',
      'İTÜ-AYAZAĞA 1',
      'İTÜ-AYAZAĞA 2',
      'HACIOSMAN',
    ],
  ),
  MetroLine(
    name: 'M3',
    stations: [
      'METROKENT',
      'ŞEHİR HASTANESİ - ÇAM SAKURA',
      'İKİTELLİ SANAYİ',
      'BAKIRKÖY ÖZGÜRLÜK MEYDANI',
      'İNCİRLİ',
    ],
  ),
  MetroLine(
    name: 'M4',
    stations: [
      'SABİHA GÖKÇEN',
      'KURTKÖY',
      'FEVZİ ÇAKMAK - HASTANE',
      'PENDİK 1',
      'KARTAL 1',
      'KARTAL 2',
      'SOĞANLIK',
      'HASTANE - ADLİYE 1 HASTANE TARAFI',
      'ESENKENT',
      'MALTEPE',
      'KÜÇÜKYALI',
      'BOSTANCI 1',
      'BOSTANCI 2',
      'KOZYATAĞI',
      'YENİSAHRA',
      'GÖZTEPE',
      'ÜNALAN 1',
      'ÜNALAN 2',
      'ÜNALAN 3',
      'AYRILIK ÇEŞMESİ',
      'KADIKÖY 1 – BATI GİRİŞİ-MSTOP',
      'KADIKÖY 2 – DOĞU GİRİŞİ-MÖSYÖ',
    ],
  ),
  MetroLine(
    name: 'M5',
    stations: [
      'ÜSKÜDAR 1 - MİGROS YANI 3-4 ÇIKIŞ / 27',
      'ÜSKÜDAR 2 / 1-2 ÇIKIŞ / 25',
      'ÜSKÜDAR 3 - KORİDOR YANI / 26',
      'BAĞLARBAŞI',
      'ALTUNİZADE KORİDOR',
      'BULGURLU',
      'ÜMRANİYE',
      'ÇARŞI',
      'ÇAKMAK',
      'ALTINŞEHİR',
      'DUDULLU 1',
      'DUDULLU 2',
      'NECİP FAZIL',
      'ÇEKMEKÖY',
      'SARIGAZİ 1 TURNİKE İÇİ',
      'SARIGAZİ 2 ASANSÖR YANI',
      'SANCAKTEPE',
      'SAMANDIRA MERKEZ',
    ],
  ),
  MetroLine(
    name: 'M6',
    stations: ['BOĞAZİÇİ ÜNİ.-HİSARÜSTÜ'],
  ),
  MetroLine(
    name: 'M7',
    stations: [
      'YILDIZ',
      'MECİDİYEKÖY 1 - SİMİT SARAYI - 43',
      'MECİDİYEKÖY 2 - KİTAPÇI YANI 42',
      'ŞİŞLİ-MECİDİYEKÖY 1 - ASANSÖR - 41',
      'ŞİŞLİ-MECİDİYEKÖY 2 - METROBÜS -44',
      'NURTEPE',
      'KAĞITHANE - MECİDİYEKÖY YÖNÜ',
      'KAZIM KARABEKİR',
      'KARADENİZ MAHALLESİ',
      'GÖZTEPE MAH.',
      'MAHMUTBEY 2 KORİDOR',
    ],
  ),
  MetroLine(
    name: 'M8',
    stations: ['BOSTANCI', 'KOZYATAĞI'],
  ),
  MetroLine(
    name: 'M9',
    stations: ['ATAKÖY', 'YENİBOSNA 1', 'YENİBOSNA 2'],
  ),
  MetroLine(
    name: 'F1',
    stations: ['KABATAŞ'],
  ),
];